#!/bin/sh
set -e

USE_COMPACT=y
USE_COMPACT=

BUILD_COMPACT=$USE_COMPACT

if [ $(basename "$0") = "siren" ]
then
	if [ -n "$1" ]
	then
		case "$1" in
			build)
				if [ -n "$2" ]
				then
					path=$2
				else
					path="."
				fi
				$path/build.sh
				exit $? ;;
			tag)
				ln -s $2 /var/lib/machines/$3
				if [ -n "$BUILD_COMPACT" ]
				then
					ln -s $2.compact /var/lib/machines/$3.compact
				fi
				exit 0 ;;
			prepare)
				base=$2
				cont=$3
				base_overlay=$(cat /var/lib/machines/$base/overlay)
				cd /var/lib/machines
				if [ -n "$cont" ]
				then
					id=$cont
					mkdir -p $id
					if [ -n "$USE_COMPACT" ]
					then
						mount -t overlay overlay -olowerdir=$base.compact,upperdir=$id,workdir=.work $id
					else
						mount -t overlay overlay -olowerdir=$base_overlay,upperdir=$id,workdir=.work $id
					fi
				else
					id=$base
					if [ -n "$USE_COMPACT" ]
					then
						mount -B $base.compact $id && mount -o remount,ro $id
					else
						# TODO check for : in $base_overlay, and use mount -B if there is none.
						echo "mount -t overlay overlay -olowerdir=$base_overlay $id"
						mount -t overlay overlay -olowerdir=$base_overlay $id
					fi
				fi
				exit 0 ;;
			unprepare)
				cd /var/lib/machines
				umount $2
				exit 0 ;;
		esac
	fi
	echo "Usage: $0 build/tag/prepare/unprepare"
	exit 1
fi

src=$( cd "$( dirname "$0" )" && pwd )
cd $src

id=""
base=""

function ID {
	name=$1
	version=$2

	id=$name-$version
	root=/var/lib/machines/$id

	mkdir -m 0755 -p $root

	# Enable ID <-> FROM reversal
	if [ -n "$base" ]
	then
		__mount
	fi
}

function FROM {
	base=$1
	if [ ! -d /var/lib/machines/$base ]
	then
		echo "Base not found: $base"
		exit 1
	fi
	base_overlay=$(cat /var/lib/machines/$base/overlay)
	base_version=$(cat /var/lib/machines/$base/version)

	# Enable ID <-> FROM reversal
	if [ -n "$id" ]
	then
		__mount
	fi
}

function RUN {
	systemd-nspawn -M $id $@
}

function ENABLE {
	RUN systemctl enable $1
}

storeargs() {
	printf "%q " "$@"
}

function SET {
	echo $2 > $root/$1
}

function CMD {
	storeargs exec "$@" > $root/run.sh
	chmod u+x $root/run.sh
}

function __cleanup_systemd {
	if [ "$(ls -A $root/etc/systemd/system)" ]
	then
		cp -r $root/etc/systemd/system/* $root/usr/lib/systemd/system/
		rm -rf $root/etc/systemd/system
	fi
}

function __mount {
	cd /var/lib/machines
	mkdir -p .work
	if [ -n "$USE_COMPACT" ]
	then
		mount -t overlay overlay -olowerdir=$base.compact,upperdir=$id,workdir=.work $id
	else
		mount -t overlay overlay -olowerdir=$base_overlay,upperdir=$id,workdir=.work $id
	fi
	cd $src
}

function __umount {
	if (mount | grep "overlay on $root type overlay")
	then
		umount $root
	fi
}

function __compact {
	rm -rf $root.compact

	if [ -n "$base" ]
	then
		mkdir -p $root.compact
		cp -r --reflink /var/lib/machines/$base.compact/* $root.compact
		cp -r --reflink $root/* $root.compact
	else
		ln -s $id $root.compact
	fi
}

function __save_settings {
	echo $version > $root/version
	if [ -n "$base" ]
	then
		echo $base_overlay:$id > $root/overlay
	else
		echo $id > $root/overlay
	fi
}

function __atEXIT {
	__umount
	__cleanup_systemd
	__save_settings
	if [ -n "$BUILD_COMPACT" ]
	then
		__compact
	fi
}

trap __atEXIT EXIT
